/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Gender = { 'other' : string } |
  { 'female' : null } |
  { 'male' : null };
export type MatchId = bigint;
export interface Message {
  'content' : string,
  'recipient' : Principal,
  'sender' : Principal,
  'matchId' : MatchId,
  'timestamp' : Time,
}
export interface Profile {
  'age' : bigint,
  'bio' : string,
  'photoUrls' : Array<string>,
  'principal' : Principal,
  'displayName' : string,
  'lastMessagePreview' : [] | [string],
  'interests' : Array<string>,
  'createdAt' : Time,
  'isActive' : boolean,
  'updatedAt' : Time,
  'interestedIn' : Gender,
  'gender' : Gender,
  'timestamp' : Time,
  'location' : string,
  'unreadMessagesCount' : bigint,
}
export interface Report {
  'reportedUser' : Principal,
  'note' : string,
  'timestamp' : Time,
  'reporter' : Principal,
  'reason' : string,
}
export type Time = bigint;
export interface UserProfile {
  'age' : bigint,
  'bio' : string,
  'photoUrls' : Array<string>,
  'displayName' : string,
  'interests' : Array<string>,
  'createdAt' : Time,
  'isActive' : boolean,
  'hasAgreedToTerms' : boolean,
  'updatedAt' : Time,
  'interestedIn' : Gender,
  'gender' : Gender,
  'location' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'blockUser' : ActorMethod<[Principal], undefined>,
  'getBlockedUsers' : ActorMethod<[], Array<Principal>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getConversation' : ActorMethod<[Principal], Array<Message>>,
  'getMatches' : ActorMethod<
    [],
    {
      'sent' : Array<Profile>,
      'matches' : Array<Profile>,
      'received' : Array<Profile>,
    }
  >,
  'getRecommendedProfiles' : ActorMethod<
    [
      [] | [bigint],
      [] | [bigint],
      [] | [Gender],
      [] | [Gender],
      [] | [Array<string>],
    ],
    Array<Profile>
  >,
  'getReports' : ActorMethod<[], Array<Report>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'likeProfile' : ActorMethod<[Principal], undefined>,
  'markConversationAsRead' : ActorMethod<[Principal], undefined>,
  'passProfile' : ActorMethod<[Principal], undefined>,
  'reportUser' : ActorMethod<[Principal, string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<[Principal, string], undefined>,
  'updateProfile' : ActorMethod<
    [
      string,
      bigint,
      Gender,
      Gender,
      string,
      string,
      Array<string>,
      Array<string>,
      boolean,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];