/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Gender = IDL.Variant({
  'other' : IDL.Text,
  'female' : IDL.Null,
  'male' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'age' : IDL.Nat,
  'bio' : IDL.Text,
  'photoUrls' : IDL.Vec(IDL.Text),
  'displayName' : IDL.Text,
  'interests' : IDL.Vec(IDL.Text),
  'createdAt' : Time,
  'isActive' : IDL.Bool,
  'hasAgreedToTerms' : IDL.Bool,
  'updatedAt' : Time,
  'interestedIn' : Gender,
  'gender' : Gender,
  'location' : IDL.Text,
});
export const MatchId = IDL.Nat;
export const Message = IDL.Record({
  'content' : IDL.Text,
  'recipient' : IDL.Principal,
  'sender' : IDL.Principal,
  'matchId' : MatchId,
  'timestamp' : Time,
});
export const Profile = IDL.Record({
  'age' : IDL.Nat,
  'bio' : IDL.Text,
  'photoUrls' : IDL.Vec(IDL.Text),
  'principal' : IDL.Principal,
  'displayName' : IDL.Text,
  'lastMessagePreview' : IDL.Opt(IDL.Text),
  'interests' : IDL.Vec(IDL.Text),
  'createdAt' : Time,
  'isActive' : IDL.Bool,
  'updatedAt' : Time,
  'interestedIn' : Gender,
  'gender' : Gender,
  'timestamp' : Time,
  'location' : IDL.Text,
  'unreadMessagesCount' : IDL.Nat,
});
export const Report = IDL.Record({
  'reportedUser' : IDL.Principal,
  'note' : IDL.Text,
  'timestamp' : Time,
  'reporter' : IDL.Principal,
  'reason' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'blockUser' : IDL.Func([IDL.Principal], [], []),
  'getBlockedUsers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConversation' : IDL.Func([IDL.Principal], [IDL.Vec(Message)], ['query']),
  'getMatches' : IDL.Func(
      [],
      [
        IDL.Record({
          'sent' : IDL.Vec(Profile),
          'matches' : IDL.Vec(Profile),
          'received' : IDL.Vec(Profile),
        }),
      ],
      ['query'],
    ),
  'getRecommendedProfiles' : IDL.Func(
      [
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
        IDL.Opt(Gender),
        IDL.Opt(Gender),
        IDL.Opt(IDL.Vec(IDL.Text)),
      ],
      [IDL.Vec(Profile)],
      ['query'],
    ),
  'getReports' : IDL.Func([], [IDL.Vec(Report)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'likeProfile' : IDL.Func([IDL.Principal], [], []),
  'markConversationAsRead' : IDL.Func([IDL.Principal], [], []),
  'passProfile' : IDL.Func([IDL.Principal], [], []),
  'reportUser' : IDL.Func([IDL.Principal, IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'updateProfile' : IDL.Func(
      [
        IDL.Text,
        IDL.Nat,
        Gender,
        Gender,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Bool,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Gender = IDL.Variant({
    'other' : IDL.Text,
    'female' : IDL.Null,
    'male' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'age' : IDL.Nat,
    'bio' : IDL.Text,
    'photoUrls' : IDL.Vec(IDL.Text),
    'displayName' : IDL.Text,
    'interests' : IDL.Vec(IDL.Text),
    'createdAt' : Time,
    'isActive' : IDL.Bool,
    'hasAgreedToTerms' : IDL.Bool,
    'updatedAt' : Time,
    'interestedIn' : Gender,
    'gender' : Gender,
    'location' : IDL.Text,
  });
  const MatchId = IDL.Nat;
  const Message = IDL.Record({
    'content' : IDL.Text,
    'recipient' : IDL.Principal,
    'sender' : IDL.Principal,
    'matchId' : MatchId,
    'timestamp' : Time,
  });
  const Profile = IDL.Record({
    'age' : IDL.Nat,
    'bio' : IDL.Text,
    'photoUrls' : IDL.Vec(IDL.Text),
    'principal' : IDL.Principal,
    'displayName' : IDL.Text,
    'lastMessagePreview' : IDL.Opt(IDL.Text),
    'interests' : IDL.Vec(IDL.Text),
    'createdAt' : Time,
    'isActive' : IDL.Bool,
    'updatedAt' : Time,
    'interestedIn' : Gender,
    'gender' : Gender,
    'timestamp' : Time,
    'location' : IDL.Text,
    'unreadMessagesCount' : IDL.Nat,
  });
  const Report = IDL.Record({
    'reportedUser' : IDL.Principal,
    'note' : IDL.Text,
    'timestamp' : Time,
    'reporter' : IDL.Principal,
    'reason' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'blockUser' : IDL.Func([IDL.Principal], [], []),
    'getBlockedUsers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConversation' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getMatches' : IDL.Func(
        [],
        [
          IDL.Record({
            'sent' : IDL.Vec(Profile),
            'matches' : IDL.Vec(Profile),
            'received' : IDL.Vec(Profile),
          }),
        ],
        ['query'],
      ),
    'getRecommendedProfiles' : IDL.Func(
        [
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
          IDL.Opt(Gender),
          IDL.Opt(Gender),
          IDL.Opt(IDL.Vec(IDL.Text)),
        ],
        [IDL.Vec(Profile)],
        ['query'],
      ),
    'getReports' : IDL.Func([], [IDL.Vec(Report)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'likeProfile' : IDL.Func([IDL.Principal], [], []),
    'markConversationAsRead' : IDL.Func([IDL.Principal], [], []),
    'passProfile' : IDL.Func([IDL.Principal], [], []),
    'reportUser' : IDL.Func([IDL.Principal, IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'updateProfile' : IDL.Func(
        [
          IDL.Text,
          IDL.Nat,
          Gender,
          Gender,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Bool,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };