/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export type Gender = {
    __kind__: "other";
    other: string;
} | {
    __kind__: "female";
    female: null;
} | {
    __kind__: "male";
    male: null;
};
export interface Message {
    content: string;
    recipient: Principal;
    sender: Principal;
    matchId: MatchId;
    timestamp: Time;
}
export interface Profile {
    age: bigint;
    bio: string;
    photoUrls: Array<string>;
    principal: Principal;
    displayName: string;
    lastMessagePreview?: string;
    interests: Array<string>;
    createdAt: Time;
    isActive: boolean;
    updatedAt: Time;
    interestedIn: Gender;
    gender: Gender;
    timestamp: Time;
    location: string;
    unreadMessagesCount: bigint;
}
export interface Report {
    reportedUser: Principal;
    note: string;
    timestamp: Time;
    reporter: Principal;
    reason: string;
}
export type MatchId = bigint;
export interface UserProfile {
    age: bigint;
    bio: string;
    photoUrls: Array<string>;
    displayName: string;
    interests: Array<string>;
    createdAt: Time;
    isActive: boolean;
    hasAgreedToTerms: boolean;
    updatedAt: Time;
    interestedIn: Gender;
    gender: Gender;
    location: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    blockUser(blocked: Principal): Promise<void>;
    getBlockedUsers(): Promise<Array<Principal>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getConversation(otherUser: Principal): Promise<Array<Message>>;
    getMatches(): Promise<{
        sent: Array<Profile>;
        matches: Array<Profile>;
        received: Array<Profile>;
    }>;
    getRecommendedProfiles(ageMin: bigint | null, ageMax: bigint | null, genderFilter: Gender | null, interestedInFilter: Gender | null, interestTags: Array<string> | null): Promise<Array<Profile>>;
    getReports(): Promise<Array<Report>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    likeProfile(target: Principal): Promise<void>;
    markConversationAsRead(otherUser: Principal): Promise<void>;
    passProfile(target: Principal): Promise<void>;
    reportUser(reportedUser: Principal, reason: string, note: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    sendMessage(recipient: Principal, content: string): Promise<void>;
    updateProfile(displayName: string, age: bigint, gender: Gender, interestedIn: Gender, location: string, bio: string, interests: Array<string>, photoUrls: Array<string>, confirmTerms: boolean): Promise<void>;
}
import type { Gender as _Gender, Profile as _Profile, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async blockUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.blockUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.blockUser(arg0);
            return result;
        }
    }
    async getBlockedUsers(): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlockedUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlockedUsers();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getConversation(arg0: Principal): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getConversation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConversation(arg0);
            return result;
        }
    }
    async getMatches(): Promise<{
        sent: Array<Profile>;
        matches: Array<Profile>;
        received: Array<Profile>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getMatches();
                return from_candid_record_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMatches();
            return from_candid_record_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRecommendedProfiles(arg0: bigint | null, arg1: bigint | null, arg2: Gender | null, arg3: Gender | null, arg4: Array<string> | null): Promise<Array<Profile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecommendedProfiles(to_candid_opt_n15(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n15(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n16(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n16(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n19(this._uploadFile, this._downloadFile, arg4));
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecommendedProfiles(to_candid_opt_n15(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n15(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n16(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n16(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n19(this._uploadFile, this._downloadFile, arg4));
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReports(): Promise<Array<Report>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReports();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReports();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async likeProfile(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.likeProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.likeProfile(arg0);
            return result;
        }
    }
    async markConversationAsRead(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markConversationAsRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markConversationAsRead(arg0);
            return result;
        }
    }
    async passProfile(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.passProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.passProfile(arg0);
            return result;
        }
    }
    async reportUser(arg0: Principal, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.reportUser(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reportUser(arg0, arg1, arg2);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n20(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n20(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async sendMessage(arg0: Principal, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1);
            return result;
        }
    }
    async updateProfile(arg0: string, arg1: bigint, arg2: Gender, arg3: Gender, arg4: string, arg5: string, arg6: Array<string>, arg7: Array<string>, arg8: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfile(arg0, arg1, to_candid_Gender_n17(this._uploadFile, this._downloadFile, arg2), to_candid_Gender_n17(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfile(arg0, arg1, to_candid_Gender_n17(this._uploadFile, this._downloadFile, arg2), to_candid_Gender_n17(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6, arg7, arg8);
            return result;
        }
    }
}
function from_candid_Gender_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Gender): Gender {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Profile_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Profile): Profile {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sent: Array<_Profile>;
    matches: Array<_Profile>;
    received: Array<_Profile>;
}): {
    sent: Array<Profile>;
    matches: Array<Profile>;
    received: Array<Profile>;
} {
    return {
        sent: from_candid_vec_n11(_uploadFile, _downloadFile, value.sent),
        matches: from_candid_vec_n11(_uploadFile, _downloadFile, value.matches),
        received: from_candid_vec_n11(_uploadFile, _downloadFile, value.received)
    };
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    bio: string;
    photoUrls: Array<string>;
    principal: Principal;
    displayName: string;
    lastMessagePreview: [] | [string];
    interests: Array<string>;
    createdAt: _Time;
    isActive: boolean;
    updatedAt: _Time;
    interestedIn: _Gender;
    gender: _Gender;
    timestamp: _Time;
    location: string;
    unreadMessagesCount: bigint;
}): {
    age: bigint;
    bio: string;
    photoUrls: Array<string>;
    principal: Principal;
    displayName: string;
    lastMessagePreview?: string;
    interests: Array<string>;
    createdAt: Time;
    isActive: boolean;
    updatedAt: Time;
    interestedIn: Gender;
    gender: Gender;
    timestamp: Time;
    location: string;
    unreadMessagesCount: bigint;
} {
    return {
        age: value.age,
        bio: value.bio,
        photoUrls: value.photoUrls,
        principal: value.principal,
        displayName: value.displayName,
        lastMessagePreview: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.lastMessagePreview)),
        interests: value.interests,
        createdAt: value.createdAt,
        isActive: value.isActive,
        updatedAt: value.updatedAt,
        interestedIn: from_candid_Gender_n6(_uploadFile, _downloadFile, value.interestedIn),
        gender: from_candid_Gender_n6(_uploadFile, _downloadFile, value.gender),
        timestamp: value.timestamp,
        location: value.location,
        unreadMessagesCount: value.unreadMessagesCount
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    bio: string;
    photoUrls: Array<string>;
    displayName: string;
    interests: Array<string>;
    createdAt: _Time;
    isActive: boolean;
    hasAgreedToTerms: boolean;
    updatedAt: _Time;
    interestedIn: _Gender;
    gender: _Gender;
    location: string;
}): {
    age: bigint;
    bio: string;
    photoUrls: Array<string>;
    displayName: string;
    interests: Array<string>;
    createdAt: Time;
    isActive: boolean;
    hasAgreedToTerms: boolean;
    updatedAt: Time;
    interestedIn: Gender;
    gender: Gender;
    location: string;
} {
    return {
        age: value.age,
        bio: value.bio,
        photoUrls: value.photoUrls,
        displayName: value.displayName,
        interests: value.interests,
        createdAt: value.createdAt,
        isActive: value.isActive,
        hasAgreedToTerms: value.hasAgreedToTerms,
        updatedAt: value.updatedAt,
        interestedIn: from_candid_Gender_n6(_uploadFile, _downloadFile, value.interestedIn),
        gender: from_candid_Gender_n6(_uploadFile, _downloadFile, value.gender),
        location: value.location
    };
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: string;
} | {
    female: null;
} | {
    male: null;
}): {
    __kind__: "other";
    other: string;
} | {
    __kind__: "female";
    female: null;
} | {
    __kind__: "male";
    male: null;
} {
    return "other" in value ? {
        __kind__: "other",
        other: value.other
    } : "female" in value ? {
        __kind__: "female",
        female: value.female
    } : "male" in value ? {
        __kind__: "male",
        male: value.male
    } : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Profile>): Array<Profile> {
    return value.map((x)=>from_candid_Profile_n12(_uploadFile, _downloadFile, x));
}
function to_candid_Gender_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): _Gender {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n21(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender | null): [] | [_Gender] {
    return value === null ? candid_none() : candid_some(to_candid_Gender_n17(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<string> | null): [] | [Array<string>] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    bio: string;
    photoUrls: Array<string>;
    displayName: string;
    interests: Array<string>;
    createdAt: Time;
    isActive: boolean;
    hasAgreedToTerms: boolean;
    updatedAt: Time;
    interestedIn: Gender;
    gender: Gender;
    location: string;
}): {
    age: bigint;
    bio: string;
    photoUrls: Array<string>;
    displayName: string;
    interests: Array<string>;
    createdAt: _Time;
    isActive: boolean;
    hasAgreedToTerms: boolean;
    updatedAt: _Time;
    interestedIn: _Gender;
    gender: _Gender;
    location: string;
} {
    return {
        age: value.age,
        bio: value.bio,
        photoUrls: value.photoUrls,
        displayName: value.displayName,
        interests: value.interests,
        createdAt: value.createdAt,
        isActive: value.isActive,
        hasAgreedToTerms: value.hasAgreedToTerms,
        updatedAt: value.updatedAt,
        interestedIn: to_candid_Gender_n17(_uploadFile, _downloadFile, value.interestedIn),
        gender: to_candid_Gender_n17(_uploadFile, _downloadFile, value.gender),
        location: value.location
    };
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "other";
    other: string;
} | {
    __kind__: "female";
    female: null;
} | {
    __kind__: "male";
    male: null;
}): {
    other: string;
} | {
    female: null;
} | {
    male: null;
} {
    return value.__kind__ === "other" ? {
        other: value.other
    } : value.__kind__ === "female" ? {
        female: value.female
    } : value.__kind__ === "male" ? {
        male: value.male
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
